import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { addToCart,fetchProductByUserId,updateQuantity,deleteItem, deleteAllItem } from './cartAPI';

const initialState = {
  itemsAdded: [],
  status: 'idle',
  cartLoaded:false
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const addToCartAsync = createAsyncThunk(
  'cart/addTocart',
  async (item) => {
    console.log(item);
    const response = await addToCart(item);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchProductByUserIdAsync = createAsyncThunk(
  'cart/fetchProductByUserId',
  async () => {
    const response = await fetchProductByUserId();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const updateQuantityAsync = createAsyncThunk(
  'cart/updateQuantity',
  async (item) => {
  
    const response = await updateQuantity(item);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const deleteItemAsync = createAsyncThunk(
  'cart/deleteItem',
  async (item) => {
    
    const response = await deleteItem(item);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const deleteAllItemAsync = createAsyncThunk(
  'cart/deleteAllItem',
  async () => {
  
    const response = await deleteAllItem();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const cartSlice = createSlice({
  name: 'cart',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase( addToCartAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase( addToCartAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.itemsAdded.push(action.payload);
      })
      .addCase( fetchProductByUserIdAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase( fetchProductByUserIdAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.itemsAdded=action.payload;
        state.cartLoaded=true;
      })
      .addCase( fetchProductByUserIdAsync.rejected, (state, action) => {
        state.status = 'idle';
        state.cartLoaded=true;
      })
      .addCase( updateQuantityAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase( updateQuantityAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        const index=state.itemsAdded.findIndex(item => item.id===action.payload.id);
        state.itemsAdded[index]=action.payload;
      })
      .addCase( deleteItemAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase( deleteItemAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        const index=state.itemsAdded.findIndex(item => item.id===action.payload.id);
        state.itemsAdded.splice(index, 1);
      })
      .addCase( deleteAllItemAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase( deleteAllItemAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.itemsAdded=[]
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectItems = (state) => state.cart.itemsAdded;
export const selectCartLoaded = (state) => state.cart.cartLoaded;

export default cartSlice.reducer;
